services:
  php-fpm:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    image: php:8.3.4-fpm
    volumes:
      - .:/app
    working_dir: /app
    command: ["php-fpm"]

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - .:/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm

  mysql:
    image: mysql:8.3
    volumes:
      - mysql-data:/var/lib/mysql
      - ./docker/mysql/initdb:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"

volumes:
  mysql-data: